image: syntithenai/mosquitto
manifests:
  - image: toke/mosquitto
    platform:
      architecture: amd64
      os: linux
  - image: pascaldevink/rpi-mosquitto
    platform:
      architecture: arm
      os: linux
