version: '2'

services:

    pulseaudio:
        image: syntithenai/pulseaudio
        build: ./docker-images/pulseaudio
        #privileged: true
        devices: ['/dev/snd']
        # proxy for host pulseaudio server
        #environment: ['PULSE_SERVER=192.168.1.100']
        entrypoint: ['pulseaudio']
        volumes: 
            # pulseaudio access via shared socket
            - ./pulse:/tmp/pulse
            # proxy for host pulseaudio server auth cookie
            #- /home/stever/.config/pulse/cookie:/tmp/cookie

    mosquitto:
        # see docker-compose/manifest*.yml for multi arch config
        image: syntithenai/mosquitto
        ports:
            - 1883:1883
            # websockets enabled (for browser clients)
            - 9001:9001 
        #volumes:
            #- ./data/mosquitto/data:/mqtt/data
            #- ./data/mosquitto/logs:/mqtt/logs
        #restart: always

    audioserver:
        depends_on: ['mosquitto']
        image: syntithenai/rasa
        build: ./docker-images/rasa
        working_dir: /opt/snips_audioserver
        entrypoint : ["/opt/snips_audioserver/start.sh"]
        #entrypoint: ['/bin/sleep','360000']
        volumes:
            # HOST MOUNT FOR DEVELOPMENT
            - ./docker-images/rasa/snips_audioserver:/opt/snips_audioserver
            - ./docker-images/rasa/snips_rasa_server:/opt/snips_rasa_server
            # pulseaudio access via shared socket
            - ./pulse:/tmp/pulse
            - ./docker-compose/pulse-client.conf:/etc/pulse/client.conf
            - ./snips_hotword_snowboy/asound-pulse.conf:/etc/asound.conf
       
    snowboy:
        depends_on: ['mosquitto','pulseaudio']
        #    devices: ['/dev/snd']
        build: ./docker-images/snowboy
        image: syntithenai/snowboy
        working_dir: /opt/snips_hotword_snowboy
        #entrypoint: ['/bin/sleep','3600']
        entrypoint: ['/opt/snips_hotword_snowboy/start.sh']
        volumes:
            # pulseaudio access via shared socket
            - ./pulse:/tmp/pulse
            - ./docker-compose/pulse-client.conf:/etc/pulse/client.conf
            - ./snips_hotword_snowboy/asound-pulse.conf:/etc/asound.conf
            #- ./docker-images/snowboy/snips_hotword_snowboy/asound-pulse.conf:/etc/asound.conf
            # dev mode
            - ./docker-images/snowboy/snips_hotword_snowboy:/opt/snips_hotword_snowboy
            
            
        environment:
            - MQTT_HOST=mosquitto
            - MQTT_PORT=1883
            - HOTWORD_MODEL=/opt/snips_hotword_snowboy/resources/snowboy.umdl
            - SITE_ID=default
            - LISTEN_TO=default
            - HOTWORD_ID=snowboy
            
    tts:
        depends_on: ['mosquitto','pulseaudio']
        image: syntithenai/rasa
        build: ./docker-images/rasa
        working_dir: /opt/snips_tts
        entrypoint: ['/opt/snips_tts/start.sh']
        #entrypoint: ['/bin/sleep','360000']
        volumes:
            - ./docker-images/rasa/snips_tts:/opt/snips_tts
            - ./pulse:/tmp/pulse
            - ./docker-compose/pulse-client.conf:/etc/pulse/client.conf
   
    snips:
        depends_on: ['mosquitto','pulseaudio']
        #'rasa'
        devices: ['/dev/snd']
        image: syntithenai/snips
        build: ./docker-images/snips
        # 
        command: --exclude-components snips-audio-server --exclude-components snips-analytics --exclude-components snips-tts  --exclude-components snips-hotword --exclude-components  snips-queries  -mqqt mosquitto:1883
        volumes:
            # generic model is built into image, override with other models here
            # -/home/stever/projects/snips-asr-model-en-500MB/snips-asr-model-en-500MB:/usr/share/snips/assistant/custom_asr
            # snips config
            - ./docker-compose/snips/config/assistant:/usr/share/snips/assistant
            - ./docker-compose/snips/snips.toml:/etc/snips.toml
            # pulseaudio access via shared socket
            - ./pulse:/tmp/pulse
            #- ./docker-compose/pulse-client.conf:/etc/pulse/client.conf
            - ./snips_hotword_snowboy/asound-pulse.conf:/etc/asound.conf
            - ./docker-compose/pulse-client.conf:/etc/pulse/client.conf
            
        #environment:
        #    - PULSE_SERVER=unix:/tmp/pulse/socket
            
    rasa:
        depends_on: ['mosquitto']
        image: syntithenai/rasa
        build: ./docker-images/rasa
        working_dir: /opt/snips_rasa_server
        #environment:
            #- disable_nlu=no|yes
            #- disable_core=no|yes
            #- mqtt_hostname=mosquitto
            #- mqtt_port=1883
            #- nlu_model_path=models/nlu
            #- snips_assistant_path=models/snips
            #- snips_user_id=user_Kr5A7b4OD
            #- core_model_path=models/dialog
            #- config_file=config/config.json
            #- domain_file=config/domain.yml
            #- nlu_training_file=config/nlu.md
            #- core_training_file=config/stories.md
            #- lang=en-GB
        #entrypoint : ["/opt/snips_rasa_server/start.sh"]
        entrypoint: ['/bin/sleep','360000']
        volumes:
            #- ./docker-compose/supervisor-rasa.conf:/etc/supervisor/conf.d/supervisord.conf
            #- ../docker-images/rasa/snips_rasa_nlu:/opt/rasa/snips_rasa_nlu
            #- ./rasa_musicplayer:/opt/rasa/rasa_musicplayer
            #- ./docker-compose/snips/config/assistant:/usr/share/snips/assistant
            # HOST MOUNT CONFIG
            #- ./docker-images/rasa/snips_rasa_server/config:/opt/snips_rasa_server/config
            # HOST MOUNT FOR DEVELOPMENT
            - ./docker-images/rasa/snips_rasa_server:/opt/snips_rasa_server
            #- ./docker-images/rasa/snips_rasa_server/models:/opt/snips_rasa_server/models

