version: '2'

services:

    pulseaudio:
        image: syntithenai/pulseaudio
        build: ./docker-images/pulseaudio
        devices: ['/dev/snd']
        # environment: ['PULSE_SERVER=192.168.1.100']
        # volumes: ['/home/stever/.config/pulse/cookie:/root/.config/pulse/cookie']

    mosquitto:
        # see docker-compose/manifest*.yml for multi arch config
        image: syntithenai/mosquitto
        ports:
            - 1883:1883
            - 9001:9001 
        volumes:
            - ./data/mosquitto/data:/mqtt/data
            - ./data/mosquitto/logs:/mqtt/logs
        #restart: always

    snowboy:
        depends_on: ['mosquitto']
        build: ./docker-images/snowboy
        image: syntithenai/snowboy
        working_dir: /opt/snips_hotword_snowboy
        entrypoint: ['/opt/snips_hotword_snowboy/start.sh']
        #entrypoint: ['/bin/sleep']
        #command: ['600s']
        #restart: always
        volumes:
            - /tmp/snowboylog:/tmp/snowboylog
            - ./snips_hotword_snowboy/asound-pulse.conf:/etc/asound.conf
            # dev mode
            #- ./snips_hotword_snowboy:/opt/snips_hotword_snowboy
            # auth for direct connect to pulseaudio on host
            # - /home/stever/.config/pulse/cookie:/root/.config/pulse/cookie
        environment:
            - PULSE_SERVER=pulseaudio
            - MQTT_HOST=mosquitto
            - MQTT_PORT=1883
            - HOTWORD_MODEL=/opt/snips_hotword_snowboy/resources/snowboy.umdl
            - SITE_ID=default
            - HOTWORD_ID=snowboy

    snips:
        depends_on: ['mosquitto']
        image: syntithenai/snips
        build: ./docker-images/snips
        command: --exclude-components snips-hotword --exclude-components  snips-queries -mqqt mosquitto:1883
        volumes:
            # authentication for pulse on linux laptop
            #- /home/stever/.config/pulse/cookie:/root/.config/pulse/cookie
            # generic language model
            - /home/stever/projects/snips-asr-model-en-500MB/snips-asr-model-en-500MB:/usr/share/snips/assistant/custom_asr
            ## snips config
            # assistant
            - ./docker-compose/snips/config/assistant:/usr/share/snips/assistant
            # main config
            - ./docker-compose/snips/snips.toml:/etc/snips.toml
        environment:
            - PULSE_SERVER=pulseaudio
            #192.168.1.100
        

    rasa_nlu:
        depends_on: ['mosquitto']
        image: syntithenai/rasa
        build: ./docker-images/rasa
        working_dir: /opt/rasa/snips_rasa_nlu
        environment:
            - NLU_TRAINING_FILE=/opt/rasa/data/nlu-model/stories.md
            - NLU_CONFIG_FILE=/opt/rasa/data/nlu-model/config.json
            - MQTT_HOST=mosquitto
            - MQTT_PORT=1883
            - NLU_MODEL_FOLDER=/opt/rasa/data/nlu-model/default/model_20171125-071720
        entrypoint : ["/opt/rasa/snips_rasa_nlu/rasa_nlu_server.py"]
        #entrypoint: ['/bin/bash']
        volumes:
            - ./snips_rasa_nlu:/opt/rasa/snips_rasa_nlu
            - ./rasa_musicplayer:/opt/rasa/rasa_musicplayer
            - ./docker-compose/snips/config/assistant:/usr/share/snips/assistant
            - ./data:/opt/rasa/data
            - ./docker-compose/supervisor-rasa.conf:/etc/supervisor/conf.d/supervisord.conf

